"""empty message

Revision ID: 7c08c7f24f68
Revises:
Create Date: 2020-01-20 14:02:59.543852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c08c7f24f68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=True),
    sa.Column('cost_values', sa.Float(precision=20), nullable=True),
    sa.Column('product_line', sa.String(length=36), nullable=True),
    sa.Column('unit_per_box', sa.Numeric(precision=6), nullable=True),
    sa.Column('weight_per_unit', sa.String(length=10), nullable=True),
    sa.Column('shelf_life', sa.String(length=10), nullable=True),
    sa.Column('sku', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=70), nullable=True),
    sa.Column('is_active', sa.Boolean(create_constraint=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('provider',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('fantasy_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('phone1', sa.String(length=12), nullable=True),
    sa.Column('phone2', sa.String(length=12), nullable=True),
    sa.Column('phone3', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('fantasy_name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('street', sa.String(length=150), nullable=True),
    sa.Column('zipcode', sa.String(length=8), nullable=True),
    sa.Column('neighborhood', sa.String(length=60), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('complement', sa.String(length=80), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_table('provider_category',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('provider_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_category')
    op.drop_table('address')
    op.drop_table('users')
    op.drop_table('provider')
    op.drop_table('products')
    op.drop_table('category')
    # ### end Alembic commands ###
